### ISSUE TITLE
actions/create-issue is broken for private repositories

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-probers#158]
**Description**

create-issue (in .github/actions/) has multiple issues when used in non-public repositories, at least:
* `gh issue list` requires a token _(EDIT: not true: it actually reads GITHUB_TOKEN just fine: all of the other GH_TOKEN=$GITHUB_TOKEN lines in the file are actually unnecessary)_
* `curl https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID` requires a bearer token

Fixing the bash script is certainly the quickest fix but the alternative is to rewrite this in javascript (github-script):
* create-issue is 100% GitHub integration: separating the code from the GitHub action has no advantages
* authentication would be handled by github-script so these issues would not come up
* 95% of all of that data parsing and querying in bash will not be needed: the triggering event should have the information we need to file the issue
* the issue_repository argument is almost certainly unneeded

**Comment by cpanato** [comment]
if we try to create an issue from a public repo to a private repo it will not work with the default github token, for that we will need a PAT

cc @haydentherapper @bobcallaway

**Comment by jku** [comment]
> if we try to create an issue from a public repo to a private repo it will not work with the default github token, for that we will need a PAT

This is also not supported in the current implementation and not expected by any current user AFAICT: `issue_repository` argument is used for both filing the issue and to form the links to the workflow so you can't really file an issue in another project. issue_repository must be the repo where the workflow runs.

**Comment by haydentherapper** [comment]
We only housed the GHA script here for convenience. Originally it was duplicated across a few repos. If this is straightforward let’s fix it here, otherwise we could go back to having it duplicated in PGI

**Comment by jku** [comment]
I'll take a look at refreshing create-issue tomorrow
