### ISSUE TITLE
Update probers to read from every shard

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore-probers#267]
**Description**

For Rekor, shards are all in the same database table, but each shard has different properties (e.g. one supports writes, the rest are read-only). We should probe all shards - right now, we're reading from a static range which hits the same shard always.

For the CT log, this is less critical as a shard is in a dedicated database instance, but we should still add monitoring.

**Comment by bobcallaway** [comment]
FYI: this is fixed for in-cluster probers in https://github.com/sigstore/scaffolding/pull/1333
